### ISSUE TITLE
Firmware Dump

### ISSUE THREAD

**Issue by yellowbyte** [dekuNukem/Amazon_Dash_Button#3]
I tried to dump the firmware on the Amazon Dash by accessing the JTAG pins on the board, but I got the read-out protection error. How did you bypass read-out protection?

**Comment by dekuNukem** [comment]
This dash button was from May 2015 back when it first came out, it's possible that they turned on firmware read protection in the later batches. Another possibility is maybe the tools you're using, I used ST-Link 2 on a STM32F0 discovery board and STM32 ST-Link Utility to dump it. I was using SWD instead of JTAG. So check that as well.
